# Site Settings
title: Haonan(Harry) Chen
url: http://newlifehaonan.github.io
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Haonan Chen
tagline: Data engineer | Database developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'M.S candidate of Computer Science at DePaul University CDM college | I am looking for a Database
administration, Data engineering, Web development, software development , back-end development internship.'

#sidebar links
email: HCHEN59@mail.depaul.edu
phone: 773-747-1944
website: newlifehaonan.com #do not add http://
linkedin: haonanchen
github: newlifehaonan
twitter:
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
